# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QT5Designer_ROMClient_v04-00.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(451, 573)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBoxSerial = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxSerial.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBoxSerial.setObjectName("comboBoxSerial")
        self.comboBoxSerial.addItem("")
        self.comboBoxSerial.setItemText(0, "None")
        self.horizontalLayout.addWidget(self.comboBoxSerial)
        self.buttonScan = QtWidgets.QPushButton(self.groupBox)
        self.buttonScan.setMaximumSize(QtCore.QSize(50, 16777215))
        self.buttonScan.setObjectName("buttonScan")
        self.horizontalLayout.addWidget(self.buttonScan)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.messageLog = QtWidgets.QTextEdit(self.centralwidget)
        self.messageLog.setEnabled(True)
        self.messageLog.setReadOnly(True)
        self.messageLog.setObjectName("messageLog")
        self.verticalLayout.addWidget(self.messageLog)
        self.buttonDump = QtWidgets.QPushButton(self.centralwidget)
        self.buttonDump.setObjectName("buttonDump")
        self.verticalLayout.addWidget(self.buttonDump)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 451, 29))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuBankswitching = QtWidgets.QMenu(self.menuSettings)
        self.menuBankswitching.setObjectName("menuBankswitching")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionNone = QtWidgets.QAction(MainWindow)
        self.actionNone.setObjectName("actionNone")
        self.actionF8_8KB = QtWidgets.QAction(MainWindow)
        self.actionF8_8KB.setObjectName("actionF8_8KB")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionEnabled = QtWidgets.QAction(MainWindow)
        self.actionEnabled.setObjectName("actionEnabled")
        self.actionDebug = QtWidgets.QAction(MainWindow)
        self.actionDebug.setCheckable(True)
        self.actionDebug.setObjectName("actionDebug")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menuBankswitching.addAction(self.actionNone)
        self.menuBankswitching.addAction(self.actionF8_8KB)
        self.menuSettings.addAction(self.menuBankswitching.menuAction())
        self.menuSettings.addAction(self.actionDebug)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ROMClient v04-00 - VCS Game Dumping Utility"))
        self.groupBox.setTitle(_translate("MainWindow", "Serial Port"))
        self.buttonScan.setText(_translate("MainWindow", "Scan"))
        self.buttonDump.setText(_translate("MainWindow", "Start ROM Dump"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuSettings.setTitle(_translate("MainWindow", "Setti&ngs"))
        self.menuBankswitching.setTitle(_translate("MainWindow", "&Bankswitching"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSave.setText(_translate("MainWindow", "&Save"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionNone.setText(_translate("MainWindow", "&None"))
        self.actionF8_8KB.setText(_translate("MainWindow", "&F8 (8KB)"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))
        self.actionEnabled.setText(_translate("MainWindow", "Enabled"))
        self.actionDebug.setText(_translate("MainWindow", "Enable Debugging"))

